spring:
  datasource:
    url: jdbc:h2:mem:thanos;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2

app:
  p1:
    normal: 16
    expert: 23
  p2:
    normal: 23
    expert: 26
  indicator:
    k: 1  # multiplicador simple para la barra de fase 2
